sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t defiler1/docker-react-app -f dockerfile.dev .

script:
  - docker run -e CI=true defiler1/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"
